export const patientsFilesModel = {
    newPatients:{
        id: 0,
        fullName: "",
        fatherName: "",
        personalCode: "",
        birthDate: "",
        surgeryDate: "",
        birthPlace: "",
        addressPlace: "",
        insuranceType: "",
        phoneNumber: 0,
        age: 0,
        gender: [],
        weight: 0,
        height: 0,
        BMI: "",
        doctor: "",
        medicationsReceived: "",
        previousDiseases: "",
        historyOfSurgeries: "",
        historyOfAllergies: "",
        historyOfSmoking: "",
        historyOfAlcoholConsumption: "",
        drugUseHistory: "",
        firstRecognition: "",
        signs: "",
        ASAPhysicalActivity: "",
        KOOS: "",
        KSS1: "",
        KSS2: "",
        WOMAC: "",
        PCF: "",
        preoperativeAntibiotics: "",
        kneeSkin : "",
        historyOfInjection : "",
        trust : "",
        surgicalSide: "",
        mechanicalAxis: "",
        LDFA: "",
        MPTA: "",
        alphaAngle: "",
        JCA: "",
        surgeryType: "",
        ROM : "",
        flexionContracture : "",
        Xray : "",
        preoperativeHematocrit: "",
        preoperativeHemoglobin : "",
        preoperativeWBC : "",
        plateletsBeforeSurgery: "",
        surgeon : "",
        assistantSurgeon: "",
        tourniquet: "",
        tournamentPressure: "",
        incision: "",
        approach: "",
        femoralGuide: "",
        femoralFixation: "",
        brandAndTypeFemur: "",
        femoralSize: "",
        femoralExternalRotation: "",
        femoralValuesCorrectionAngle: "",
        femoralDistalCutLateral: "",
        femoralPosteriorCutMedial: "",
        femoralAnteriorCut: "",
        femoralDefect: "",
        femoralDefectManagment: "",
        tibialGuide: "",
        tibialFixation : "",
        brandAndTypeOfTibial : "",
        tibialSize : "",
        tibialSlope: "",
        proximalTibialCutMedial: "",
        proximalTibialCutLateral: "",
        tibialDefect: "",
        tibialDefectManagment: "",
        pattelarResurfacing: "",
        pattelarFacetectomy: "",
        lateralRetinacularRelease : "",
        polyType : "",
        polyBrand : "",
        polySize: "",
        stemFemor : "",
        stemTibial : "",
        posteriorCapsuleRelease: "",
        medialRelease : "",
        lateralRelease: "",
        pieCrust : "",
        reductionOsteotomy : "",
        cementedOrNonCemented  : "",
        dren : "",
        anticoagulantsInWard: "",
        hospitalizationDate : "",
        DurationHospitalization : "",
        bloodInjection: "",
        complicationsDospitalization : "",
        anesthesiaType: "",
        wound: "",
        ROMComplications: "",
        postOpScores  : "",
        KOOS: "",
        KSS1: "",
        WOMAC: "",
        causesRoizen: "",
        spacerType : "",
        kneeInjuryAndOsteoarthritisOutcomeScoreKOOS: "",
        KneeSocietyScoreKSS1: "",
        KneeSocietyScoreKSS2: "",
        westernOntarioAndMcMasterUniversitiesArthritisIndexWOMAC: "",
        itemShortFormSurveySF36PCF: "",
        rangeOfMotionROM: "",
        flexionContracture : "",
        Xray : "",
        preoperativeHematocrit: "",
        preoperativeHemoglobin : "",
        preoperativeWBC : "",
        plateletsBeforeSurgery: ""
    }
}